name: CI_KalinichenkoArtem_3-21

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create build directory
        run: mkdir -p build

      - name: Configure CMake
        run: cmake -S . -B build

      - name: Build the project
        run: cmake --build build

      - name: Run the executable
        run: |
          echo "Running the program..."
          ./build/TTC || echo "Executable ran without crashing."

